Failure # 1 (occurred at 2024-03-11_16-44-53)
The actor died because of an error raised in its creation task, [36mray::MyTrainableClass.__init__()[39m (pid=26484, ip=127.0.0.1, actor_id=2e8af695ba0b7ff72362e16b01000000, repr=<hyperparameter_tuning.MyTrainableClass object at 0x145a18820>)
  File "/Users/nicolafraccarolo/miniforge3/envs/ml-env/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "hyperparameter_tuning/hyperparameter_tuning.py", line 48, in setup
    model.load_model(models_folder, model_name, self.device)
  File "/Users/nicolafraccarolo/Documents/GitHub/SDE-Net/model/gan_model.py", line 846, in load_model
    torch.load(str((Path(folder) / generator_filename).resolve()),
  File "/Users/nicolafraccarolo/miniforge3/envs/ml-env/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/nicolafraccarolo/miniforge3/envs/ml-env/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/nicolafraccarolo/miniforge3/envs/ml-env/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nicolafraccarolo/Documents/GitHub/SDE-Net/hyperparameter_tuning/trained_models/generator_SUD_v2'
